### ISSUE TITLE
[Bug] MusicBee scrobbler crashes when playing an album with Unicode characters

### ISSUE THREAD

**Issue by ghost** [ModalSeoul/Weeb.FM#21]
Traceback (most recent call last):
  File "MusicBee.py", line 63, in <module>
  File "MusicBee.py", line 59, in check_musicbee
  File "MusicBee.py", line 39, in scrobble
  File "c:\python35-32\lib\encodings\cp437.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode character '\xc3' in position 12347: character maps to <undefined>
Failed to execute script MusicBee

Furthermore it seems to also happen when playing an album that has a number in the title

Example: V4MP1R3S

**Comment by ModalSeoul** [comment]
Unicode I understand. Numbers shouldn't cause a crash, though.

**Comment by ModalSeoul** [comment]
Solved a few days ago. Forgot to close.
